# NumPy

[NumPy](https://numpy.org) (oder Numpy) ist eine lineare Algebra-Bibliothek für Python. Sehr wichtig, da fast alle Bibliotheken im PyData-Ökosystem auf NumPy als einen ihrer Hauptbausteine vertrauen.

Numpy ist außerdem unglaublich schnell, da es Bindungen an C-Bibliotheken hat. 
**Warum Numpy anstelle von Python-Arrays -> gerne [selbst recherchieren](https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists)! ;)**

Hier nur eine Einführung in die Grundlagen von Numpy.
    - Schritt Nr. 1 -> Installieren

**via poetry**: ```poetry add numpy```

**direkt via pip**: ```pip install numpy```

## Verwendung von Numpy

Numpy muss zuerst importiert werden! Typischerweise importieren wir NumPy als **np**

In [36]:
import numpy as np

Numpy ist sehr mächtig. Wir werden hier allerdings nur die für uns wichtigen Konzepte behandeln:
    - Vektoren
    - Arrays
    - Matrizen
    - Zufallszahlengenerierung
    
**Numpy Arrays sind für uns am wichtigsten.**
Numpy Arrays gibt es im Wesentlichen in zwei Varianten: **Vektoren und Matrizen.**
Vektoren sind eindimensionale Arrays und Matrizen sind zweidimensionale Arrays (eine Matrix kann dennoch immer noch nur eine Zeile oder eine Spalte haben!).

#### Numpy Arrays erstellen

Wir könnne eine Python-Liste nehmen und sie in ein Numpy Array umwandeln.

In [37]:
liste = [1,2,3,4,5]

In [38]:
liste

[1, 2, 3, 4, 5]

In [39]:
np.array(liste)

array([1, 2, 3, 4, 5])

In [40]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [41]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Es gibt viele verschiedene Möglichkeiten ein Array automatisch erstellen zu lassen mit bereits vorhandenen Methoden in Numpy!**

#### arange

Liefert gleichmäßig verteilte Werte (d.h. Stützstellen) innerhalb eines bestimmten **halboffenen** Intervalls **[start, stop)** mit einem in **steps** bestimmten Abstand und folgt dabei dem Syntax: np.arrange(start, stop, steps)

Achtung in Matlab und R: abgeschlossenes Intervall

In [42]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

#### zeros and ones

Erzeugt Arrays von Nullen oder Einsen!

In [44]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [46]:
np.ones(3)

array([1., 1., 1.])

In [47]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace

Liefert gleichmäßig verteilte Zahlen (d.h. äquidistante Stützstellen) über ein bestimmtes Intervall. `linspace` legt den Fokus auf die Anzahl der Stützstellen, `arange` dahingegen auf die Abstände.

In [48]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

#### eye
Erstellt eine Identitätsmatrix mit 1 auf der Diagonalen und 0 sonst.

In [49]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random
Numpy bietet viele verschiedene Möglichkeiten ein Array mit Zufallszahlen zu erzeugen. Es handelt sich dabei im **Pseudozufallszahlen**, die von einem [Zufallszahlengenerator](https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator) ```np.random.default_rng``` erzeugt werden. 

#### random

Erstellt ein Array der gegebenen Form und füllet es mit Stichproben aus einer gleichmäßigen Verteilung über[0, 1).

In [50]:
rng = np.random.default_rng()
rng.random(2)

array([0.15076596, 0.66170719])

In [51]:
rng.random((3,5))

array([[0.25250385, 0.4993074 , 0.56469033, 0.52779184, 0.41616422],
       [0.892422  , 0.17956504, 0.55816816, 0.24803367, 0.30034867],
       [0.86812971, 0.16861169, 0.24815972, 0.12686045, 0.29908154]])

#### randn

Stichprobe von der Normalverteilung

In [52]:
rng.normal(2)

2.191854215797941

In [53]:
rng.normal(loc=10, scale=2, size=5)

array([ 7.64953892,  9.09113209,  9.51894756,  9.56655299, 10.41388169])

#### randint
Liefert zufällige Ganzzahlen von niedrig (inklusive) bis hoch (exklusiv).

In [54]:
rng.integers(1,100)

6

In [55]:
rng.integers(low=1, high=100, size=10)

array([33, 81, 37, 11,  2, 43, 21, 91, 30, 46])

Weitere Verteilungsbeispiele
* beta(a, b, size)
* binomial(n, p, size)
* chisquare(degree_of_freedom, size)
* poisson(lamda, size)

### Array Attribute und Methoden

In [56]:
arr = np.arange(25)
ranarr = rng.integers(0,50,10)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [58]:
ranarr

array([37, 11, 25, 36, 13, 23, 10,  0,  5, 11])

#### Reshape
Ändert die Form eines Arrays

numpy.reshape(a, newshape, order='C')
* **a**: array to be reshabed
* **newshape**: int (then 1-D array) or tuple of integers; eindimensional kann durch -1 erreicht werden
* **order**: 
    * **'C'** letzter Index wechselst am schnellsten bis zum ersten Index wechselt am langsamsten
    * **'F'** erster Index wechselt am schnelslten bis zum letzten Index wechselt am langsamsten

In [59]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max, min, argmax, argmin
Dies sind nützliche Methoden zum Auffinden von Maximal- oder Minimalwerten. Oder um ihre Indexpositionen mit argmin oder argmax zu finden.

In [60]:
ranarr.max()

37

In [61]:
ranarr.argmax()

0

In [62]:
ranarr.min()

0

In [63]:
ranarr.argmin()

7

#### Form (Shape)
Die Form ist ein Attribut oder Eigenschaft eines Arrays und gibt als Tuple die Dimensionen zurück

In [64]:
arr.shape

(25,)

In [65]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [66]:
arr.reshape(1,25).shape

(1, 25)

In [67]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [68]:
arr.reshape(25,1).shape

(25, 1)

In [69]:
# Als Vektor
arr.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
arr.reshape(-1).shape

(25,)

#### dtype
Gibt an welcher Datentyp sich im Array befindet

In [71]:
arr.dtype

dtype('int64')

## NumPy Indexing und Selection

In [72]:
arr[4]

4

In [73]:
arr[1:5]

array([1, 2, 3, 4])

### Broadcasting
Numpy Arrays unterscheiden sich von einer normalen Python-Liste durch ihre Fähigkeit zum "broadcasten". Dabei wird das kleinere Array entlang des größeren "gebroadcasted", sodass die Arraygrößen passend sind.

In [74]:
arr[0:6]=100

In [75]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [76]:
# Neu initialisieren um den Effekt zu veranschaulichen
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [78]:
#Ausschnitt ändern
slice_of_arr[:]=66

slice_of_arr

array([66, 66, 66, 66, 66, 66])

**Änderung auch in dem Orginal Array zu erkennen -> Numpy macht keine Kopien sondern arbeitet an dem Original (Vermeidung von Speicher-Problemen)**

In [79]:
arr

array([66, 66, 66, 66, 66, 66,  6,  7,  8,  9, 10])

In [80]:
# So kann man eine Kopie erstellen
arr_copy = arr.copy()

arr_copy

array([66, 66, 66, 66, 66, 66,  6,  7,  8,  9, 10])

### Indexing zweidimensionales Array

Array[row][col] oder Array[row,col]

In [81]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [82]:
arr_2d[1]

array([20, 25, 30])

In [83]:
arr_2d[1][0]

20

In [84]:
arr_2d[1,0]

20

In [85]:
#Matrix
arr2d = np.zeros((10,10))

In [86]:
#Mit Daten befüllen

for i in range(len(arr2d)):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [87]:
#Auch nur ein Teil daraus (bestimmte Reihen)
arr2d[[1,2,6,8]]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

### Selection

In [88]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [90]:
bool_arr = arr>4

In [91]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [92]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [93]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Numpy Operationen

#### Arithmetik 

In [95]:
arr = np.arange(0,10)

In [96]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [98]:
# Warnung division by zero. Aber kein Error!
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [99]:
# Auch nur eine Warnung kein Error (infinity)
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [100]:
arr**4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

#### Andere Numpy Operationen

In [101]:
# Wurzel ziehen
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [102]:
# e^ berechnen
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [103]:
#Logarithmus
np.log(arr)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])